name: Nightly

on:
  workflow_dispatch:
  schedule:
    # Every night at 03:00
    - cron: '0 3 * * *'

jobs:
  minVersion:
    runs-on: ubuntu-latest
    container:
      image: cirrusci/flutter:1.26.0-17.5.pre
    steps:
      - uses: actions/checkout@v2.3.4
        with:
          ref: stable
      - name: Flutter version
        run: flutter doctor -v
      - name: Download dependencies
        run: sudo --preserve-env=PATH env flutter packages get
      - name: Analyze
        run: sudo --preserve-env=PATH env dartanalyzer --fatal-infos --fatal-warnings .
      - name: Test
        run: sudo --preserve-env=PATH env flutter test
      - name: Build
        run: cd example && sudo --preserve-env=PATH env flutter build web

  stable:
    runs-on: ubuntu-latest
    container:
      image: cirrusci/flutter:stable
    steps:
      - uses: actions/checkout@v2.3.4
        with:
          ref: stable
      - name: Flutter version
        run: flutter doctor -v
      - name: Download dependencies
        run: sudo --preserve-env=PATH env flutter packages get
      - name: Analyze
        run: sudo --preserve-env=PATH env dartanalyzer --fatal-infos --fatal-warnings .
      - name: Test
        run: sudo --preserve-env=PATH env flutter test
      - name: Build
        run: cd example && sudo --preserve-env=PATH env flutter build web

  beta:
    runs-on: ubuntu-latest
    container:
      image: cirrusci/flutter:beta
    steps:
      - uses: actions/checkout@v2.3.4
        with:
          ref: beta
      - name: Flutter version
        run: flutter doctor -v
      - name: Download dependencies
        run: sudo --preserve-env=PATH env flutter packages get
      - name: Analyze
        run: sudo --preserve-env=PATH env flutter analyze --fatal-infos --fatal-warnings .
      - name: Test
        run: sudo --preserve-env=PATH env flutter test
      - name: Build
        run: cd example && sudo --preserve-env=PATH env flutter build web

  dev:
    runs-on: ubuntu-latest
    container:
      image: cirrusci/flutter:dev
    steps:
      - uses: actions/checkout@v2.3.4
        with:
          ref: dev
      - name: Flutter version
        run: flutter doctor -v
      - name: Download dependencies
        run: sudo --preserve-env=PATH env flutter packages get
      - name: Analyze
        run: sudo --preserve-env=PATH env flutter analyze --fatal-infos --fatal-warnings .
      - name: Test
        run: sudo --preserve-env=PATH env flutter test
      - name: Build
        run: cd example && sudo --preserve-env=PATH env flutter build web
