name: Pull Requests

on:
  pull_request:
  push:
    branches:
      - stable
      - beta
      - dev

jobs:
  pr-min:
    runs-on: ubuntu-latest
    container:
      image: cirrusci/flutter:1.26.0-17.5.pre
    if: github.base_ref == 'stable' || github.ref == 'refs/heads/stable'
    steps:
      - uses: actions/checkout@v2.3.4
      - name: Flutter version
        run: flutter doctor -v
      - name: Download dependencies
        run: sudo --preserve-env=PATH env flutter packages get
      - name: Analyze
        run: sudo --preserve-env=PATH env dartanalyzer --fatal-infos --fatal-warnings .
      - name: Test
        run: sudo --preserve-env=PATH env flutter test
      - name: Build
        run: cd example && sudo --preserve-env=PATH env flutter build web

  pr-stable:
    runs-on: ubuntu-latest
    container:
      image: cirrusci/flutter:stable
    if: github.base_ref == 'stable' || github.ref == 'refs/heads/stable'
    steps:
      - uses: actions/checkout@v2.3.4
      - name: Flutter version
        run: flutter doctor -v
      - name: Download dependencies
        run: sudo --preserve-env=PATH env flutter packages get
      - name: Analyze
        run: sudo --preserve-env=PATH env dartanalyzer --fatal-infos --fatal-warnings .
      - name: Test
        run: sudo --preserve-env=PATH env flutter test
      - name: Build
        run: cd example && sudo --preserve-env=PATH env flutter build web
      - name: Check formatting
        run: sudo --preserve-env=PATH env dartfmt --dry-run --set-exit-if-changed .

  pr-beta:
    runs-on: ubuntu-latest
    container:
      image: cirrusci/flutter:beta
    if: github.base_ref == 'beta' || github.ref == 'refs/heads/beta'
    steps:
      - uses: actions/checkout@v2.3.4
      - name: Flutter version
        run: flutter doctor -v
      - name: Download dependencies
        run: sudo --preserve-env=PATH env flutter packages get
      - name: Analyze
        run: sudo --preserve-env=PATH env flutter analyze --fatal-infos --fatal-warnings .
      - name: Test
        run: sudo --preserve-env=PATH env flutter test
      - name: Build
        run: cd example && sudo --preserve-env=PATH env flutter build web
      - name: Check formatting
        run: sudo --preserve-env=PATH env dartfmt --dry-run --set-exit-if-changed .

  pr-dev:
    runs-on: ubuntu-latest
    container:
      image: cirrusci/flutter:dev
    if: github.base_ref == 'dev' || github.ref == 'refs/heads/dev'
    steps:
      - uses: actions/checkout@v2.3.4
      - name: Flutter version
        run: flutter doctor -v
      - name: Download dependencies
        run: sudo --preserve-env=PATH env flutter packages get
      - name: Analyze
        run: sudo --preserve-env=PATH env flutter analyze --fatal-infos --fatal-warnings .
      - name: Test
        run: sudo --preserve-env=PATH env flutter test
      - name: Build
        run: cd example && sudo --preserve-env=PATH env flutter build web
      - name: Check formatting
        run: sudo --preserve-env=PATH env dartfmt --dry-run --set-exit-if-changed .
